server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 9030
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 20MB
logging:
  level:
    com:
      website:
        user: trace